### ISSUE TITLE
Support MacOS/Windows

### ISSUE THREAD

**Issue by Mk555** [Mk555/pagerduty-tui#11]

**Comment by Mk555** [comment]
I was not able to test on MacOS/Windows, if anyone can help and post the issues below it would be helpful !

**Comment by Mk555** [comment]
Validated on Windows !

**Comment by ChristianWitts** [comment]
Just built this for macOS arm64. TUI launches, refreshes just fine.
I don't have an unacknowledged incident to test the ACK currently.
<Enter> does not open a browser to the incident, and busy checking the code to look for a fix to submit a PR.

**Comment by Mk555** [comment]
Thanks for your tests ! 

I think you need to adapt this function to work on MacOS : 
https://github.com/Mk555/pagerduty-tui/blob/main/src/utils.rs#L14-L17

If you send me a command to open the default browser on MacOS I can add the OS check and add the command

**Comment by ChristianWitts** [comment]
On macOS you can use `/usr/bin/open` which will open in the default browser.

I also noticed you should allow configuration for the PagerDuty organization here https://github.com/Mk555/pagerduty-tui/blob/main/src/pagerduty.rs#L15 via the configuration file and config struct.

**Comment by Mk555** [comment]
I created a branch for the issue of organization : 
https://github.com/Mk555/pagerduty-tui/tree/11-support-macoswindows

I will test that tomorrow, but you can add the parameter `pagerduty_domain` in you config with the name of your organization

**Comment by Mk555** [comment]
I also added the open command for macOS, let me know how it works !

**Comment by ChristianWitts** [comment]
Confirmed that open in browser now works on macOS 👍🏻
