### ISSUE TITLE
[Feature] Toggle between Open Incidents for All Users and Assigned to Me

### ISSUE THREAD

**Issue by paulateffodio** [Mk555/pagerduty-tui#19]
As a user, I would like a filter/hotkey that will allow me to display open incidents for all users and just those assigned to me.  

From a devops perspective, I need to be able to monitor any triggered or acknowledged incidents regardless of who is on-call and assigned to the incident.

This filter should be persistent between refreshes.

**Comment by Mk555** [comment]
Hello !

I created a new branch to test the new feature : https://github.com/Mk555/pagerduty-tui/tree/all_incidents

Let me know if you can't test, and I'll create a new release and fix it later

Thanks for your idea :)

**Comment by paulateffodio** [comment]
I tested and the filter works for changing to all users. Thanks for implementing my feature request!  One thing, is it possible to toggle the text in the Navbar for `(G) Show all` to change to `(G) Show user` when you are viewing all incidents? I notice that the assigned user disappears when you are in user view, but being able to glance at the (G) text would be great.

Thanks again!

**Comment by Mk555** [comment]
Hi @paulateffodio !

I pushed a change to always show the assignee.

But the other feature to change the name of the option when the mode is change will require a little bit more work. I don't have time for now to work on this feature, do you agree to split this to a new feature request ?

Thank you for your support !

**Comment by paulateffodio** [comment]
Yep! Sounds good.
